#!/bin/fish

cd ~/hacksussex-2025

if ! test -d .venv/
    python3 -m venv .venv > /dev/null
end

source .venv/bin/activate.fish > /dev/null



cd ~/hacksussex-2025/backend
pip install -r requirements.txt > /dev/null
rm ./database.db 2> /dev/null


fastapi dev main.py
